### ISSUE TITLE
consistent_active_orbital_spaces.py can not run correctly

### ISSUE THREAD

**Issue by wangdu817** [qcscine/autocas#11]
Hi, 
I want to try the consistent_active_orbital_spaces in autocas, i use the consistent_active_orbital_spaces.py by input
"python consistent_active_orbital_spaces.py -m casscf -b cc-ptdz 992954475746614962061_r12_insertion_R_3_4_12.xyz 992954475746614962061.xyz"

and the error returned:
"Final energy evaulation method: casscf
Calculating only mean field.
Starting initial orbital calculation.

Starting MOLCAS:
/share/home/wd/OpenMolcas/pymolcas -b 1 -f
MOLCAS environment:
MOLCAS_PROJECT:  0
MOLCAS_MEM:      12000
WorkDir:         /mnt/ssd/wd/cases/casscf_test/molcas/scratch
MOLCAS_NPROCS:   1
OMP_NUM_THREADS: 1
QCMaquis_CPU:    1
Initial orbitals finished.
Calculating only mean field.
Starting initial orbital calculation.

Starting MOLCAS:
/share/home/wd/OpenMolcas/pymolcas -b 1 -f
MOLCAS environment:
MOLCAS_PROJECT:  1
MOLCAS_MEM:      12000
WorkDir:         /mnt/ssd/wd/cases/casscf_test/molcas/scratch
MOLCAS_NPROCS:   1
OMP_NUM_THREADS: 1
QCMaquis_CPU:    1
Initial orbitals finished.
Traceback (most recent call last):
  File "consistent_active_orbital_spaces.py", line 348, in <module>
    main(os.path.dirname(os.path.abspath(__file__)))
  File "consistent_active_orbital_spaces.py", line 274, in main
    serenity = Serenity(molecules, settings)
  File "/share/home/wd/anaconda3/envs/autocas/lib/python3.7/site-packages/scine_autocas/interfaces/serenity/__init__.py", line 122, in __init__
    settings = spy.Settings()
AttributeError: module 'serenipy' has no attribute 'Settings'"

Does it mean that I need to install serenity?

Du Wang

**Comment by moritzBens** [comment]
Hi Du Wang,
Yes, Serenity (https://github.com/qcserenity/serenity) is required for the orbital mapping, which ensures that the same orbitals are selected for the CAS. If you have installed Serenity, ensure you sourced the `serenity.sh` script in your Serenity directory.

Best
Moritz

**Comment by moritzBens** [comment]
To make matters worse, the file `autocas/scine_autocas/interfaces/serenity/__init__.py` contains two typos. The next release will fix these typos. Here is the corrected file (GitHub restricts the file type, so here is the `__init__.py` as a zip): 
[patch.zip](https://github.com/qcscine/autocas/files/14021188/patch.zip)

Replace the file at `autocas/scine_autocas/interfaces/serenity/__init__.py` with the `__init__.py` in the archive.

Moritz

**Comment by wangdu817** [comment]
Hi @ @moritzBens,
I have successfully compiled the serenity and replace the file with your guidance, but same  no attribute error was occurred, my serenipy (0.2.6) was installed from pip, and does not include a setting.py file in the serenipy dir.  Could you please give me more suggestions?

**Comment by moritzBens** [comment]
To my knowledge, there is no support for Serenity on Pypi. The serenipy version you installed by be related to a different software. To install Serenity's Python bindings, you have to compile them with Serenity (either use `ccmake` manually or add the `-DSERENITY_PYTHON_BINDINGS=ON` flag to the `cmake` call, as documented in Serenity's README). After installation, the Python bindings will be added to your `PYTHONPATH` if you source the `serenity.sh` script.

**Comment by wangdu817** [comment]
Hi @moritzBens 
 Thank you for your help, but again, I got some other error during the calculation,
"Traceback (most recent call last):
  File "consistent_active_orbital_spaces.py", line 348, in <module>
    main(os.path.dirname(os.path.abspath(__file__)))
  File "consistent_active_orbital_spaces.py", line 283, in main
    orbital_map, unmappable_orbitals = serenity.get_orbital_map()
  File "/share/home/wd/anaconda3/envs/autocas/lib/python3.7/site-packages/scine_autocas/interfaces/serenity/__init__.py", line 212, in get_orbital_map
    return self.build_orbital_map(fragments)
  File "/share/home/wd/anaconda3/envs/autocas/lib/python3.7/site-packages/scine_autocas/interfaces/serenity/__init__.py", line 338, in build_orbital_map
    gdos = spy.GeneralizedDOSTask_R(self.systems, fragments)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. serenipy.GeneralizedDOSTask_R(arg0: std::vector<std::shared_ptr<Serenity::SystemController>, std::allocator<std::shared_ptr<Serenity::SystemController> > >, arg1: std::vector<std::shared_ptr<Serenity::SystemController>, std::allocator<std::shared_ptr<Serenity::SystemController> > >)

Invoked with: [<serenipy.System object at 0x2b4c78e5c770>, <serenipy.System object at 0x2b4c8ee6d630>], [<serenipy.System object at 0x2b4c8ee9ebb0>, <serenipy.System object at 0x2b4c8ee9eb70>, <serenipy.System object at 0x2b4c8ee9ebf0>, <serenipy.System object at 0x2b4c8ee9ec30>, <serenipy.System object at 0x2b4c8ee9ecb0>, <serenipy.System object at 0x2b4c8ee9eb30>, <serenipy.System object at 0x2b4c8ee9ecf0>, <serenipy.System object at 0x2b4c8ee9ed30>]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module."
I think the stl.h, chrono.h and functional.h have been included during the cmake process(verified from the cmakecache), which was automatically made during the installation of serenity. Do you have some further suggestions on my problem? 
Moreover, I think there are still some errors in the file of "interfaces/serenity/__init__.py", the serenipy has no "readOrbitalsIOTask_U", I change it to"OrbitalsIOTask_U", which can work now.

**Comment by moritzBens** [comment]
The error message nails the problem. The `#include <pybind11/stl.h>` is missing in `serenity/src/tasks/GeneralizedDOSTask_python.cpp`. I tested the code with gcc/g++ 11.4 on Ubuntu and did not encounter this problem. But with different compilers and operating systems, pybind sometimes behaves slightly differently. A quick fix could be to add the  `#include <pybind11/stl.h>` to the file. Here is the updated source file: 
[GeneralizedDOSTask_python.zip](https://github.com/qcscine/autocas/files/14137130/GeneralizedDOSTask_python.zip)

Replace the file with the same name in `serenty/src/tasks/` and recompile/re-install serenity.

Alternatively, you could use gcc/g++.

**Comment by weymutht** [comment]
> To make matters worse, the file `autocas/scine_autocas/interfaces/serenity/__init__.py` contains two typos. The next release will fix these typos. Here is the corrected file (GitHub restricts the file type, so here is the `__init__.py` as a zip): [patch.zip](https://github.com/qcscine/autocas/files/14021188/patch.zip)
> 
> Replace the file at `autocas/scine_autocas/interfaces/serenity/__init__.py` with the `__init__.py` in the archive.
> 
> Moritz

We have just released autoCAS 2.2.0, which fixes the typos in `autocas/scine_autocas/interfaces/serenity/__init__.py`.
